### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Fantasy2121** [GB28181/GB28181.Solution#1]
Hello, I have some questions. Do you have contact information?My email address is 1339931310@qq.com

**Comment by crazybber** [comment]
any question ? you can describe it ,directly ,here.

**Comment by Fantasy2121** [comment]
程序运行后，获取视频流的时候  
 if (!ffimp_init()) {
                    throw new Exception("ffimp init error"); 会报错误
                }
说是newcjj.dll引用的问题，请问是该引用的版本问题吗，项目生成是X86的

**Comment by crazybber** [comment]
应该检查ffmpeg 相关的组件在你的开发环境是否工作，原始项目winform 中的video功能部分，可能缺少相关的动态依赖库。
当前项目聚焦于.net core2.1+ 服务平台，winform 相关的video 功能部分，暂未使用。

**Comment by Fantasy2121** [comment]
我用的是迁移之前那个项目，然后重新生成的vs2010版的，是否是vs版本太低的问题呢？之前已经调试成功了，当我想引用您的项目重新做控件项目时运行就出错了

**Comment by crazybber** [comment]
或许是的，原始项目使用，vs2013 编译。
如果你目前暂时只关心，winform 相关的video部分，可以把client 相关的project单独拿出来解决问题。

**Comment by 19931806840** [comment]
请问一下在网站中调取视频部分出错是什么原因呢

**Comment by Fantasy2121** [comment]
您好，有个问题需要咨询您：我把播放视频功能改成了多窗口同时播放，但我同时播放两个视频5分钟左右的时候PlayerControl控件中的SwsScale.cs类中Convert()方法会报内存溢出的错误，并且，视频播放界面的播放速度越来越慢，实际10秒的视频却用了15秒才播完，CPU占用也很大，同时播放两个视频就达到了70%，我觉得可能是PlayerControl控件播放视频时有内存没有及时释放的问题，请问，您知道这是什么原因引起的吗？

**Comment by crazybber** [comment]
@Fantasy2121  该仓库的基础代码中来自上游仓库，播放视频业务的form部分功能，我们未曾用到，暂时未深究过。初步看起来仅用于测试用，并非用于生产环境，问题应不止于内存泄漏和CPU占用过高，如有进一步发现，也希望得到进一步分享。

**Comment by Fantasy2121** [comment]
您好，请问您这个平台有没有实现将自身作为下级平台，向其他上级平台注册、传设备列表、传视频流的功能？

**Comment by crazybber** [comment]
@Fantasy2121 代码本身就是支持相关功能的，具体的业务场景的相关feature正在开发，当前仓库中还未添加该部分功能。

**Comment by crazybber** [comment]
@Fantasy2121 另，在前述讨论中，SLW.MeidaNetEnginee和GB28181.Client两个project涉及到的视频播放相关的问题，如果已解决，也欢迎PR，一起共参与贡献。
