### ISSUE TITLE
GB28181.SIPRequest中存在两个Header, 其中一个为空，造成SIPTransaction类构造时报错异常

### ISSUE THREAD

**Issue by itproductivity** [GB28181/GB28181.Solution#16]
protected SIPTransaction(
            SIPTransport sipTransport,
            SIPRequest transactionRequest,
            SIPEndPoint outboundProxy)
        {
            try
            {
                if (sipTransport == null)
                {
                    throw new ArgumentNullException("A SIPTransport object is required when creating a SIPTransaction.");
                }
                else if (transactionRequest == null)
                {
                    throw new ArgumentNullException("A SIPRequest object must be supplied when creating a SIPTransaction.");
                }
                else if (**transactionRequest.Header**.Vias.TopViaHeader == null)
                {
                    throw new ArgumentNullException("The SIP request must have a Via header when creating a SIPTransaction.");
                }

**Comment by crazybber** [comment]
你能帮忙提个修复的PR吗？

**Comment by ly114kuang** [comment]
我也遇到这个问题，但是我不会修复，能帮忙解决吗？

**Comment by d8kzdzt** [comment]
我也遇到这个问题，但是我不会修复，能帮忙解决吗？

**Comment by crazybber** [comment]
try latest.
