### ISSUE TITLE
SIPRequest.cs中有请求无限嵌套导致程序崩溃问题

### ISSUE THREAD

**Issue by nirdino** [GB28181/GB28181.Solution#19]
您好！这段代码是不是有点问题？有请求的情况下，嵌套导致程序崩溃。
源码位置：GB28181.Solution\GB28181.SIPSorcery\core\SIP\SIPRequest.cs
图片：
![QQ图片20210116005327](https://user-images.githubusercontent.com/5669487/104755353-44be5500-5795-11eb-99ad-e06ed1dcef80.png)

**Comment by crazybber** [comment]
嵌套中的那个希望是调用基类中的方法，可以修复一下逻辑，如果不需要也可以拿掉。

**Comment by nirdino** [comment]
明白，我这边已经处理掉这个~

**Comment by crazybber** [comment]
可以提一个PR。

> 明白，我这边已经处理掉这个~
