### ISSUE TITLE
(0xc0000005) 'Access violation'

### ISSUE THREAD

**Issue by L60008028** [GB28181/GB28181.Solution#21]
WinTool 闪退，单独启动GB28181.Server 也会闪退，报错如下：
程序“[161960] iisexpress.exe”已退出，返回值为 -1073741819 (0xc0000005) 'Access violation'。

**Comment by ycq323** [comment]
这个闪退的问题有解决的吗？

**Comment by crazybber** [comment]
闪退已修，有复现再提。
