### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by 19931806840** [GB28181/GB28181.Solution#3]
你好，我有个问题想要咨询您：
我在您编写的程序上添加了部分功能：将获取到的相机视频流数据通过TCP协议传输到一个新项目用于显示视频，播放控件同样使用您编写的PlayerControl控件，程序运行在win7X64系统、x64平台上，但，在程序运行到调用PlayerControl控件播放视频时，执行ffimp_init()操作出现了调用NewCJJ.dll错误：试图加载格式不正确的程序。我用depends工具查看发现是DLL版本与我的程序不符的问题（我已尝试将程序运行在X86，无法启动程序），请问，您能否提供给我一份NewCJJ.dll的x64版本？非常感谢！

**Comment by 19931806840** [comment]
您好，我的邮箱是779135675@qq.com，您能帮我解答一下这个问题吗？

**Comment by crazybber** [comment]
如果原始项目基于x86编译，而你需要解决video相关的问题，建议你也follow， 在此基础上解决问题。
当前项目聚焦于.net core2.1+ 服务平台，winform 相关的video 功能部分，暂未使用到，如果能解决问题，也希望能得到你的分享。

**Comment by 19931806840** [comment]
请问一下在网站中想要获取视频，却出错了是什么原因呢

**Comment by 19931806840** [comment]
出现的异常：iexplore.exe已附加有调试器，但没有将该调试器配置为调试此未经处理的异常，若要调试此异常，必须分离当前的调试器
当前调试器配置为调试使用Microsoft.Net Framwork1.0、1.1或2.0版的代码。而正在从.NET Framwork 4.0版代码引发未经处理的异常。

**Comment by crazybber** [comment]
不是很清楚你的应用场景，建议问题最好附上必要的截图。

**Comment by crazybber** [comment]
如果没有问题，将关闭当前issue，如有新问题，可另行讨论。
