### ISSUE TITLE
Big Shot~HELP

### ISSUE THREAD

**Issue by xruihu** [GB28181/GB28181.Solution#4]
有联系方式吗有偿求教

**Comment by crazybber** [comment]
什么情况？

**Comment by xruihu** [comment]
现在这个里面有一些问题，一是设备管理的服务没有，还有一个解决方案在报错

**Comment by xruihu** [comment]
有联系方式吗大佬需要请教

**Comment by xruihu** [comment]
我的邮箱263700343@qq.com

**Comment by xruihu** [comment]
想看看您Grpc客户端调用的例子

**Comment by crazybber** [comment]
> 现在这个里面有一些问题，一是设备管理的服务没有，还有一个解决方案在报错

设备管理服务，需要另行开发，当前的开源代码里面只提供了设备管理的部分接口(gRPC).

报错，可以贴出来看看。

**Comment by crazybber** [comment]
> 想看看您Grpc客户端调用的例子

grpc 参考官网教程即可，本代码相关的proto文件在: Proto.Grpc/Protos/ 文件夹内。

**Comment by xruihu** [comment]
现在这个28181的服务大概能承载多少路视频并发呢

**Comment by crazybber** [comment]
> 现在这个28181的服务大概能承载多少路视频并发呢

视频部分是做测试的，如果要做单独的流媒体功能，建议你结合目标架构重新做该部分功能的代码设计。
