### ISSUE TITLE
这个项目支持级联互联吗

### ISSUE THREAD

**Issue by nanguantong** [GB28181/GB28181.Solution#8]
代码里面貌似没有看到相关的项

**Comment by crazybber** [comment]
支持，但实现的不是很完全，当前实现侧重在了设备接入，自己可以照着套路完善一下。

**Comment by nanguantong** [comment]
> 支持，但实现的不是很完全，当前实现侧重在了设备接入，自己可以照着套路完善一下。

主要是哪个类？SIPRegistrarBindingsManager
